### ISSUE TITLE
Program Not Listening! 

### ISSUE THREAD

**Issue by RohanDas28** [MadhavSharma08/JARVIS-PERSONAL-ASSISTANT#1]
The Program was also not working On My Pc I Have Fixed It By Installing The Latest Version Of PYAudio Manually.
Here Is The Stackoverflow Page For That https://stackoverflow.com/questions/52283840/i-cant-install-pyaudio-on-windows-how-to-solve-error-microsoft-visual-c-14

**Comment by MadhavSharma08** [comment]
****Is it working now??****

**Comment by RohanDas28** [comment]
Yes I have Tested It! It Works Both on My Laptop and PC

**Comment by MadhavSharma08** [comment]
Bro i have already installed pyaudio and it is showing requirement already satisfied

**Comment by RohanDas28** [comment]
Try One Thing Comment Everything And Try By Uncommenting! If and Elif Sentence And Run The Code. So You will find that faulty part!. But Its working Well In My Pc and laptop! idk why it is not working on your pc
